### ISSUE TITLE
Seeing defunct git processes accumulate

### ISSUE THREAD

**Issue by d11wtq** [gordonwritescode/gitty#26]
When I use gitty to clone git repositories in a long-running node process, I notice that defunct git processes show up in `ps`. It appears gitty isn't checking the exit status of `git` and reaping children.

**Comment by gordonwritescode** [comment]
I highly suspect this was an issue with my usage of `pty.js`, which implemented a pseudo TTY interface for handling authenticated `clone`, `push`, and `pull` over SSH (by simulating the user typing their username and password). This is no longer supported due to it being a security vulnerability and has since been removed entirely (`gitty` no longer has any dependencies), so I'm closing this issue.
